install:
  - wget http://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz -O - | sudo tar zxf - --strip-components 1 -C /usr/local
  - yes | sudo add-apt-repository ppa:cmrx64/cargo
  - sudo apt-get update
  - sudo apt-get install cargo
script:
  - cargo build
  - make all
os:
  - linux
